(test
 (name application_test)
 (modules application_test)
 (deps
  (glob_files fixtures/*))
 (libraries rescript_linter))

(test
 (name watch_test)
 (modules watch_test)
 (libraries rescript_linter))

(test
 (name linter_test)
 (modules linter_test)
 (libraries rescript_linter))

(test
 (name blank_lines_test)
 (modules blank_lines_test)
 (libraries rescript_linter))

(test
 (name fixer_test)
 (modules fixer_test)
 (libraries rescript_linter unix))

(test
 (name no_object_magic_test)
 (modules no_object_magic_test)
 (libraries rescript_linter))

(test
 (name rules_of_hooks_test)
 (modules rules_of_hooks_test)
 (libraries rescript_linter))

(test
 (name no_unhandled_throws_test)
 (modules no_unhandled_throws_test)
 (libraries rescript_linter))

(test
 (name throws_model_test)
 (modules throws_model_test)
 (libraries rescript_linter))

(test
 (name no_unsafe_test)
 (modules no_unsafe_test)
 (libraries rescript_linter))

(test
 (name no_unsafe_inventory_test)
 (modules no_unsafe_inventory_test)
 (deps
  (glob_files ../vendor/rescript/packages/@rescript/runtime/*.res)
  (glob_files ../vendor/rescript/packages/@rescript/runtime/*.resi))
 (libraries rescript_linter))

(cram
 (deps
  %{bin:rescript-lint}
  watch_cli.sh
  (glob_files fixtures/*)))
