(test
 (name application_test)
 (modules application_test)
 (deps
  (glob_files fixtures/*))
 (libraries rescript_linter))

(test
 (name linter_test)
 (modules linter_test)
 (libraries rescript_linter))

(test
 (name no_object_magic_test)
 (modules no_object_magic_test)
 (libraries rescript_linter))

(test
 (name no_unsafe_test)
 (modules no_unsafe_test)
 (libraries rescript_linter))

(test
 (name no_unsafe_inventory_test)
 (modules no_unsafe_inventory_test)
 (deps
  (glob_files ../vendor/rescript/packages/@rescript/runtime/*.res)
  (glob_files ../vendor/rescript/packages/@rescript/runtime/*.resi))
 (libraries rescript_linter))

(cram
 (deps
  %{bin:rescript-lint}
  (glob_files fixtures/*)))
